title: Zhenxin Qin(秦祯欣)'s Homepage
page-top-title: Zhenxin Qin(秦祯欣)
top-section-bg-text: Mechanical Engineering
home-subtitle: Zhenxin Qin&ensp;|&ensp;秦祯欣
copyright-text: '&copy; Zhenxin Qin 2024-2025. All Rights Reserved.'
